server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.51.119:3306/androidProject
    username: androidProject
    password: androidProject
mybatis:
  typeAliasesPackage: luoma.test_cms.Entity
  mapperLocations: classpath:Mapper/*.xml